# 测试目标与 CTest 注册：普通单测在这里维护，AI gateway 测试目标由 ai_gateway.cmake 创建。

# sylar_add_test_executable(test1 "tests/test.cc")
# sylar_add_test_executable(test_config "tests/test_config.cc")
# sylar_add_test_executable(test_thread "tests/test_thread.cc")
# sylar_add_test_executable(test_util "tests/test_util.cc")
# sylar_add_test_executable(test_fiber "tests/test_fiber.cc")
# sylar_add_test_executable(test_scheduler "tests/test_scheduler.cc")
# sylar_add_test_executable(test_iomanager "tests/test_iomanager.cc")
# sylar_add_test_executable(test_hook "tests/test_hook.cc")
# sylar_add_test_executable(test_address "tests/test_address.cc")
# sylar_add_test_executable(test_socket "tests/test_socket.cc")
# sylar_add_test_executable(test_bytearray "tests/test_bytearray.cc")
# sylar_add_test_executable(test_http "tests/test_http.cc")
# sylar_add_test_executable(test_http_parser "tests/test_http_parser.cc")
# sylar_add_test_executable(test_tcp_server "tests/test_tcp_server.cc")
# sylar_add_executable(echo_server "examples/echo_server.cc" sylar "${LIBS}")
# sylar_add_test_executable(test_http_server "tests/test_http_server.cc")
sylar_add_test_executable(test_http_connection "tests/test_http_connection.cc")
sylar_add_test_executable(test_http_session_recv_error "tests/test_http_session_recv_error.cc")
sylar_add_test_executable(test_http_request_options "tests/test_http_request_options.cc")
sylar_add_test_executable(test_http_attempt_outcome "tests/test_http_attempt_outcome.cc")
sylar_add_test_executable(test_http_client "tests/test_http_client.cc")
sylar_add_test_executable(test_http_circuit_breaker "tests/test_http_circuit_breaker.cc")
sylar_add_test_executable(test_http_concurrency_limiter "tests/test_http_concurrency_limiter.cc")
sylar_add_test_executable(test_http_load_balance_client "tests/test_http_load_balance_client.cc")
sylar_add_test_executable(test_worker_group "tests/test_worker_group.cc")
sylar_add_test_executable(test_env_config "tests/test_env_config.cc")
sylar_add_test_executable(test_http_connection_pool "tests/test_http_connection_pool.cc")

add_library(test_module_lifecycle_plugin SHARED "tests/test_module_lifecycle_plugin.cc")
target_link_libraries(test_module_lifecycle_plugin PRIVATE sylar)
set_target_properties(test_module_lifecycle_plugin PROPERTIES
    LIBRARY_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/bin/test_module_lifecycle_plugins
)
sylar_add_test_executable(test_module_lifecycle "tests/test_module_lifecycle.cc"
                          test_module_lifecycle_plugin)

sylar_add_test_executable(test_tls_client_options "tests/test_tls_client_options.cc")
sylar_add_test_executable(test_module_config_timing "tests/test_module_config_timing.cc")

sylar_register_unit_test(test_worker_group)
sylar_register_unit_test(test_http_session_recv_error)
sylar_register_unit_test(test_env_config)
sylar_register_unit_test(test_http_connection_pool)
sylar_register_unit_test(test_http_attempt_outcome)
sylar_register_unit_test(test_module_lifecycle)
sylar_register_unit_test(test_tls_client_options)
sylar_register_unit_test(test_module_config_timing)
sylar_register_unit_test(test_ai_gateway_route_registry)
sylar_register_unit_test(test_ai_gateway_protocol)
sylar_register_unit_test(test_ai_gateway_servlet)
sylar_register_unit_test(test_ai_gateway_load_balance)
sylar_register_unit_test(test_ai_gateway_real_provider)
sylar_register_unit_test(test_ai_gateway_real_runtime)
sylar_register_unit_test(test_ai_gateway_status)
sylar_register_unit_test(test_ai_gateway_demo_servlet)
sylar_register_unit_command(startup_missing_config $<TARGET_FILE:bin_sylar> -s -c
                            /tmp/sylar-missing-config)
set_tests_properties(startup_missing_config PROPERTIES WILL_FAIL TRUE)
# sylar_add_test_executable(test_uri "tests/test_uri.cc")
# sylar_add_test_executable(test_daemon "tests/test_daemon.cc")
# sylar_add_test_executable(test_application "tests/test_application.cc")
# sylar_add_test_executable(test_ws_server "tests/test_ws_server.cc")
# sylar_add_test_executable(test_ws_client "tests/test_ws_client.cc")
